add_requires("libsdl")

target("altair_vm_relaxed")
	set_kind("shared")
	set_languages("c++17")
	add_files("src/*.cpp")
	add_headerfiles("src/*.hpp")
	add_deps("altair_vm_base", { public = true })
	add_defines("AR_EXPORT")
	add_packages("libsdl", { public = true })
