
#define AX_OPID_RA_W 0x01
#define AX_OPID_RA_R 0x02
#define AX_OPID_RB 0x04
#define AX_OPID_RC 0x08

#define AX_OPID_VR 0x10
#define AX_OPID_VA 0x20
#define AX_OPID_RX 0x40
#define AX_OPID_IM 0x80

#define AX_STALL_CMP 0x40
#define AX_STALL_CMP_END 0x47
#define AX_STALL_BRU 0x50
#define AX_STALL_BRU_END 0x5F

#define AX_ACCU 61

#define AX_ALU_CYCLE 3
#define AX_FPU_CYCLE 4
#define AX_PQ_CYCLE 4
#define AX_VPQ_CYCLE 5

static const uint8_t opcode1_rw[] =
{
	//ALU-A
	0b0000,
	AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_RA_W,

	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,

	AX_OPID_RA_W,
	AX_OPID_RA_W,
	0b0000,
	0b0000,

	AX_OPID_RA_W,
	AX_OPID_RA_W,
	AX_OPID_RA_W,
	AX_OPID_RC,

	//ALU-B
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,

	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,

	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,

	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,
	0b0000,
	0b0000,
	0b0000,

	//LSU-A
	AX_OPID_RA_W|AX_OPID_RX,
	AX_OPID_RA_R|AX_OPID_RX,
	AX_OPID_RA_W|AX_OPID_VA|AX_OPID_RX,
	AX_OPID_RA_R|AX_OPID_VA|AX_OPID_RX,

	AX_OPID_RA_W|AX_OPID_RX,
	AX_OPID_RA_R|AX_OPID_RX,
	AX_OPID_RA_W|AX_OPID_VA|AX_OPID_RX,
	AX_OPID_RA_R|AX_OPID_VA|AX_OPID_RX,

	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_RA_R|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_RA_W|AX_OPID_VA|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_RA_R|AX_OPID_VA|AX_OPID_RB|AX_OPID_RC,

	AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_RA_R|AX_OPID_RB,
	AX_OPID_RA_W|AX_OPID_VA|AX_OPID_RB,
	AX_OPID_RA_R|AX_OPID_VA|AX_OPID_RB,

	//LSU
	0b0000,
	0b0000,
	0b0000,
	0b0000,

	0b0000,
	0b0000,
	0b0000,
	0b0000,

	//Prefetch
	0b0000,
	0b0000,
	0b0000,
	0b0000,

	0b0000,
	0b0000,
	0b0000,
	0b0000,

	//CMP
	AX_OPID_RA_R|AX_OPID_RB,
	0b0000,
	AX_OPID_RA_R,
	AX_OPID_RA_R,

	AX_OPID_VR|AX_OPID_RA_R|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_R|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_R,
	AX_OPID_VR|AX_OPID_RA_R,

	//Other

	0x00,
	AX_OPID_RA_R,
	0x00,
	0x00,

	//BRU
	0x00,
	0x00,
	0x00,
	0x00,

	0x00,
	0x00,
	0x00,
	0x00,
	0x00,
	0x00,
	0x00,
	0x00,

	0x00,
	0x00,
	0x00,
	0x00,
	0x00,
	0x00,
	0x00,
	0x00,

	//VFPU-A
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,

	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,

	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,

	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,

	//VFPU-B
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W,
	AX_OPID_VR|AX_OPID_RA_W,

	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,

	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,

	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
};

static const uint8_t opcode2_rw[] =
{
	//ALU-A
	0b0000,
	AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_RA_W,

	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,

	AX_OPID_RA_W,
	AX_OPID_RA_W,
	0b0000,
	0b0000,

	AX_OPID_RA_W,
	AX_OPID_RA_W,
	AX_OPID_RA_W,
	AX_OPID_RC,

	//ALU-B
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,

	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,
	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_IM,

	0b0000,
	0b0000,
	0b0000,
	0b0000,

	0b0000,
	0b0000,
	0b0000,
	0b0000,

	//LSU-A
	AX_OPID_RA_W|AX_OPID_RX,
	AX_OPID_RA_R|AX_OPID_RX,
	AX_OPID_RA_W|AX_OPID_VA|AX_OPID_RX,
	AX_OPID_RA_R|AX_OPID_VA|AX_OPID_RX,

	AX_OPID_RA_W|AX_OPID_RX,
	AX_OPID_RA_R|AX_OPID_RX,
	AX_OPID_RA_W|AX_OPID_VA|AX_OPID_RX,
	AX_OPID_RA_R|AX_OPID_VA|AX_OPID_RX,

	AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_RA_R|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_RA_W|AX_OPID_VA|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_RA_R|AX_OPID_VA|AX_OPID_RB|AX_OPID_RC,

	AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_RA_R|AX_OPID_RB,
	AX_OPID_RA_W|AX_OPID_VA|AX_OPID_RB,
	AX_OPID_RA_R|AX_OPID_VA|AX_OPID_RB,


	//Prefetch
	0b0000,
	0b0000,
	0b0000,
	0b0000,

	0b0000,
	0b0000,
	0b0000,
	0b0000,




	//EFU
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,

	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,

	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,

	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,

	//FPU-Double
	AX_OPID_VR|AX_OPID_RA_W,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB|AX_OPID_RC,

	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,

	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,

	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
	AX_OPID_VR|AX_OPID_RA_W|AX_OPID_RB,
};


