
#define AX_DEC_RX  0x8000

static const uint16_t opcode1[] =
{
	//ALU-A
    AX_EXE_ALU+AX_OPCODE_NOP,
    AX_EXE_ALU+AX_OPCODE_SEXT,
    AX_EXE_ALU+AX_OPCODE_BOOL,
    AX_EXE_ALU+AX_OPCODE_SMOVE+AX_IMM_U16BITS,

    AX_EXE_ALU+AX_OPCODE_SLTS,
    AX_EXE_ALU+AX_OPCODE_SLTU,
    AX_EXE_ALU+AX_OPCODE_SLTS+AX_IMM_S10BITS,
    AX_EXE_ALU+AX_OPCODE_SLTU+AX_IMM_U10BITS,

    AX_EXE_ALU+AX_OPCODE_MOVE+AX_IMM_OS18BITS,
    AX_EXE_ALU+AX_OPCODE_MOVE+AX_IMM_U18BITS,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    AX_EXE_ALU+AX_OPCODE_MOVEINS,
    AX_EXE_ALU+AX_OPCODE_MOVECYCLE,
    AX_EXE_ALU+AX_OPCODE_MOVERI1,
    AX_EXE_ALU+AX_OPCODE_MOVERI2,

    //ALU-B
    AX_EXE_ALU+AX_OPCODE_ADD+AX_IMM_U9BITS,
    AX_EXE_ALU+AX_OPCODE_SUB+AX_IMM_U9BITS,
    AX_EXE_ALU+AX_OPCODE_XOR+AX_IMM_U9BITS,
    AX_EXE_ALU+AX_OPCODE_OR+AX_IMM_U9BITS,
    AX_EXE_ALU+AX_OPCODE_AND+AX_IMM_U9BITS,
    AX_EXE_ALU+AX_OPCODE_LSL+AX_IMM_U9BITS,
    AX_EXE_ALU+AX_OPCODE_ASR+AX_IMM_U9BITS,
    AX_EXE_ALU+AX_OPCODE_LSR+AX_IMM_U9BITS,

    AX_EXE_ALU+AX_OPCODE_MUL+AX_IMM_S9BITS,
    AX_EXE_ALU+AX_OPCODE_DIVS+AX_IMM_S9BITS,
    AX_EXE_ALU+AX_OPCODE_DIVU+AX_IMM_U9BITS,
    AX_EXE_ALU+AX_OPCODE_REMS+AX_IMM_S9BITS,
    AX_EXE_ALU+AX_OPCODE_REMU+AX_IMM_U9BITS,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    //LSU-A
    AX_EXE_LSU+AX_OPCODE_LD+AX_IMM_U16BITS+AX_DEC_RX,
    AX_EXE_LSU+AX_OPCODE_ST+AX_IMM_U16BITS+AX_DEC_RX,
    AX_EXE_LSU+AX_OPCODE_LDV+AX_IMM_U16BITS+AX_DEC_RX,
    AX_EXE_LSU+AX_OPCODE_STV+AX_IMM_U16BITS+AX_DEC_RX,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    //LSU-B
    AX_EXE_LSU+AX_OPCODE_LD,
    AX_EXE_LSU+AX_OPCODE_ST,
    AX_EXE_LSU+AX_OPCODE_LDV,
    AX_EXE_LSU+AX_OPCODE_STV,

    AX_EXE_LSU+AX_OPCODE_LD+AX_IMM_S10BITS,
    AX_EXE_LSU+AX_OPCODE_ST+AX_IMM_S10BITS,
    AX_EXE_LSU+AX_OPCODE_LDV+AX_IMM_S10BITS,
    AX_EXE_LSU+AX_OPCODE_STV+AX_IMM_S10BITS,

    AX_EXE_LSU+AX_OPCODE_LDDMA,
    AX_EXE_LSU+AX_OPCODE_STDMA,
    AX_EXE_LSU+AX_OPCODE_LDDMA+AX_IMM_U10BITS,
    AX_EXE_LSU+AX_OPCODE_STDMA+AX_IMM_U10BITS,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    //CMP
    AX_EXE_ALU+AX_OPCODE_CMP,
    AX_EXE_ALU+AX_OPCODE_CMPFR+AX_IMM_U16BITS,
    AX_EXE_ALU+AX_OPCODE_CMP+AX_IMM_S18BITS,
    AX_EXE_ALU+AX_OPCODE_CMP+AX_IMM_U18BITS,

    AX_EXE_VFPU+AX_OPCODE_FCMP,
    AX_EXE_VFPU+AX_OPCODE_DCMP,
    AX_EXE_VFPU+AX_OPCODE_FCMP+AX_IMM_HTOF,
    AX_EXE_VFPU+AX_OPCODE_DCMP+AX_IMM_HTOD,

    AX_EXE_ALU+AX_OPCODE_ENDP,
    AX_EXE_ALU+AX_OPCODE_EXE,
    AX_EXE_LSU+AX_OPCODE_WAIT,
    AX_OPCODE_UNK,

    AX_EXE_BRU+AX_OPCODE_RET,
    AX_EXE_BRU+AX_OPCODE_RETI,
    AX_EXE_BRU+AX_OPCODE_SYSCALL,
    AX_EXE_BRU+AX_OPCODE_INT,

    AX_EXE_BRU+AX_OPCODE_BNE+AX_IMM_S22BITS,
    AX_EXE_BRU+AX_OPCODE_BEQ+AX_IMM_S22BITS,

    AX_EXE_BRU+AX_OPCODE_BL+AX_IMM_S22BITS,
    AX_EXE_BRU+AX_OPCODE_BLE+AX_IMM_S22BITS,
    AX_EXE_BRU+AX_OPCODE_BG+AX_IMM_S22BITS,
    AX_EXE_BRU+AX_OPCODE_BGE+AX_IMM_S22BITS,

    AX_EXE_BRU+AX_OPCODE_BLS+AX_IMM_S22BITS,
    AX_EXE_BRU+AX_OPCODE_BLES+AX_IMM_S22BITS,
    AX_EXE_BRU+AX_OPCODE_BGS+AX_IMM_S22BITS,
    AX_EXE_BRU+AX_OPCODE_BGES+AX_IMM_S22BITS,

    AX_EXE_BRU+AX_OPCODE_BRA+AX_IMM_S22BITS,
    AX_EXE_BRU+AX_OPCODE_LOOP+AX_IMM_S22BITS,

    AX_EXE_BRU+AX_OPCODE_JMP+AX_IMM_S22BITS,
    AX_EXE_BRU+AX_OPCODE_JMPBR+AX_IMM_S22BITS,
    AX_EXE_BRU+AX_OPCODE_CALL+AX_IMM_S22BITS,
    AX_EXE_BRU+AX_OPCODE_CALLBR+AX_IMM_S22BITS,

    //VFPU-A
    AX_EXE_VFPU+AX_OPCODE_FADD,
    AX_EXE_VFPU+AX_OPCODE_FSUB,
    AX_EXE_VFPU+AX_OPCODE_FMUL,
    AX_EXE_VFPU+AX_OPCODE_FMADD,

    AX_EXE_VFPU+AX_OPCODE_VFADD,
    AX_EXE_VFPU+AX_OPCODE_VFSUB,
    AX_EXE_VFPU+AX_OPCODE_VFMUL,
    AX_EXE_VFPU+AX_OPCODE_VFMADD,

    AX_EXE_VFPU+AX_OPCODE_VFADDS,
    AX_EXE_VFPU+AX_OPCODE_VFSUBS,
    AX_EXE_VFPU+AX_OPCODE_VFMULS,
    AX_EXE_VFPU+AX_OPCODE_VFMADDS,

    AX_EXE_VFPU+AX_OPCODE_FSUB,
    AX_EXE_VFPU+AX_OPCODE_VFSUB,
    AX_EXE_VFPU+AX_OPCODE_VFSUBS,
    AX_EXE_VFPU+AX_OPCODE_VFSHUFFLE,

    //VFPU-B
    AX_EXE_VFPU+AX_OPCODE_FMOVE,
    AX_EXE_VFPU+AX_OPCODE_VFMOVE,
    AX_EXE_VFPU+AX_OPCODE_FMOVE+AX_IMM_HTOF,
    AX_EXE_VFPU+AX_OPCODE_VFMOVE+AX_IMM_HTOF,

    AX_EXE_VFPU+AX_OPCODE_FNEG,
    AX_EXE_VFPU+AX_OPCODE_FABS,
    AX_EXE_VFPU+AX_OPCODE_VFNEG,
    AX_EXE_VFPU+AX_OPCODE_VFABS,

    AX_EXE_VFPU+AX_OPCODE_VFTOH,
    AX_EXE_VFPU+AX_OPCODE_VHTOF,
    AX_EXE_VFPU+AX_OPCODE_VFTOI,
    AX_EXE_VFPU+AX_OPCODE_VITOF,
    AX_EXE_VFPU+AX_OPCODE_VFTOD,
    AX_EXE_VFPU+AX_OPCODE_VDTOF,
    AX_EXE_VFPU+AX_OPCODE_FMIN,
    AX_EXE_VFPU+AX_OPCODE_FMAX,
};

static const uint16_t opcode2[] =
{
	//ALU-A
    AX_EXE_ALU+AX_OPCODE_NOP,
    AX_EXE_ALU+AX_OPCODE_SEXT,
    AX_EXE_ALU+AX_OPCODE_BOOL,
    AX_EXE_ALU+AX_OPCODE_SMOVE+AX_IMM_U16BITS,

    AX_EXE_ALU+AX_OPCODE_SLTS,
    AX_EXE_ALU+AX_OPCODE_SLTU,
    AX_EXE_ALU+AX_OPCODE_SLTS+AX_IMM_S10BITS,
    AX_EXE_ALU+AX_OPCODE_SLTU+AX_IMM_U10BITS,

    AX_EXE_ALU+AX_OPCODE_MOVE+AX_IMM_OS18BITS,
    AX_EXE_ALU+AX_OPCODE_MOVE+AX_IMM_U18BITS,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    AX_EXE_ALU+AX_OPCODE_MOVEINS,
    AX_EXE_ALU+AX_OPCODE_MOVECYCLE,
    AX_EXE_ALU+AX_OPCODE_MOVERI1,
    AX_EXE_ALU+AX_OPCODE_MOVERI2,

    //ALU-B
    AX_EXE_ALU+AX_OPCODE_ADD+AX_IMM_U9BITS,
    AX_EXE_ALU+AX_OPCODE_SUB+AX_IMM_U9BITS,
    AX_EXE_ALU+AX_OPCODE_XOR+AX_IMM_U9BITS,
    AX_EXE_ALU+AX_OPCODE_OR+AX_IMM_U9BITS,
    AX_EXE_ALU+AX_OPCODE_AND+AX_IMM_U9BITS,
    AX_EXE_ALU+AX_OPCODE_LSL+AX_IMM_U9BITS,
    AX_EXE_ALU+AX_OPCODE_ASR+AX_IMM_U9BITS,
    AX_EXE_ALU+AX_OPCODE_LSR+AX_IMM_U9BITS,

    AX_EXE_ALU+AX_OPCODE_MUL+AX_IMM_S9BITS,
    AX_EXE_ALU+AX_OPCODE_DIVS+AX_IMM_S9BITS,
    AX_EXE_ALU+AX_OPCODE_DIVU+AX_IMM_U9BITS,
    AX_EXE_ALU+AX_OPCODE_REMS+AX_IMM_S9BITS,
    AX_EXE_ALU+AX_OPCODE_REMU+AX_IMM_U9BITS,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    //LSU-A
    AX_EXE_LSU+AX_OPCODE_LD+AX_IMM_U16BITS+AX_DEC_RX,
    AX_EXE_LSU+AX_OPCODE_ST+AX_IMM_U16BITS+AX_DEC_RX,
    AX_EXE_LSU+AX_OPCODE_LDV+AX_IMM_U16BITS+AX_DEC_RX,
    AX_EXE_LSU+AX_OPCODE_STV+AX_IMM_U16BITS+AX_DEC_RX,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    //LSU-B
    AX_EXE_LSU+AX_OPCODE_LD,
    AX_EXE_LSU+AX_OPCODE_ST,
    AX_EXE_LSU+AX_OPCODE_LDV,
    AX_EXE_LSU+AX_OPCODE_STV,

    AX_EXE_LSU+AX_OPCODE_LD+AX_IMM_S10BITS,
    AX_EXE_LSU+AX_OPCODE_ST+AX_IMM_S10BITS,
    AX_EXE_LSU+AX_OPCODE_LDV+AX_IMM_S10BITS,
    AX_EXE_LSU+AX_OPCODE_STV+AX_IMM_S10BITS,

    AX_EXE_LSU+AX_OPCODE_LDDMA,
    AX_EXE_LSU+AX_OPCODE_STDMA,
    AX_EXE_LSU+AX_OPCODE_LDDMA+AX_IMM_U10BITS,
    AX_EXE_LSU+AX_OPCODE_STDMA+AX_IMM_U10BITS,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    //----
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    //----
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    //EFU
    AX_EXE_EFU+AX_OPCODE_FDIV,
    AX_EXE_EFU+AX_OPCODE_FSQRT,
    AX_EXE_EFU+AX_OPCODE_DDIV,
    AX_EXE_EFU+AX_OPCODE_DSQRT,

    AX_EXE_EFU+AX_OPCODE_FATAN,
    AX_EXE_EFU+AX_OPCODE_FATAN2,
    AX_EXE_EFU+AX_OPCODE_FEXP,
    AX_OPCODE_UNK,

    AX_EXE_EFU+AX_OPCODE_FSUM,
    AX_EXE_EFU+AX_OPCODE_FIPR,
    AX_EXE_EFU+AX_OPCODE_FSIN,
    AX_EXE_EFU+AX_OPCODE_DSIN,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    //FPU-D
    AX_EXE_FPUD+AX_OPCODE_DMOVE,
    AX_EXE_FPUD+AX_OPCODE_DADD,
    AX_EXE_FPUD+AX_OPCODE_DSUB,
    AX_EXE_FPUD+AX_OPCODE_DMUL,

    AX_EXE_FPUD+AX_OPCODE_DABS,
    AX_EXE_FPUD+AX_OPCODE_DNEG,
    AX_EXE_FPUD+AX_OPCODE_DMIN,
    AX_EXE_FPUD+AX_OPCODE_DMAX,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,

    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
    AX_OPCODE_UNK,
};
